### ISSUE TITLE
java.io.NotSerializableException: Object of org.apache.spark.streaming.dstream.ShuffledDStream is being serialized  possibly as a part of closure of an RDD operation. This is because  the DStream object is being referred to from within the closure.  Please rewrite the RDD operation inside this DStream to avoid this.  This has been enforced to avoid bloating of Spark tasks  with unnecessary objects.

### ISSUE THREAD

**Issue by Hungsiro506** [mkuthan/example-kafka#3]
Hi, I got this problem when trying  to send msg  to kafka. Iam using spark 2.0.0, and kafka 1.0. It seems that the kafka producer can not be serialized correctly.

**Comment by OneCricketeer** [comment]
@Hungsiro506 Can you share the relevant code that you have?

The solution is right in the error message. 

> ShuffledDStream is being serialized possibly as a part of closure of an RDD operation. This is because the DStream object is being referred to from within the closure. __*Please rewrite the RDD operation inside this DStream to avoid this*__

**Comment by felipegutierrez** [comment]
I got the same problem. here is my stacktrace:
```
$ sbt
[info] Loading project definition from /Users/felipe.o.gutierrez/workspace/example-spark-kafka/project
[info] Set current project to example-spark-kafka (in build file:/Users/felipe.o.gutierrez/workspace/example-spark-kafka/)
> run
[info] Running example.WordCountJob 
[info] 21:47:16.844 [main] WARN  o.a.hadoop.util.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[info] 21:47:17.673 [sparkDriverActorSystem-akka.actor.default-dispatcher-4] INFO  akka.event.slf4j.Slf4jLogger - Slf4jLogger started
[info] 21:47:17.729 [sparkDriverActorSystem-akka.actor.default-dispatcher-2] INFO  Remoting - Starting remoting
[info] 21:47:17.904 [sparkDriverActorSystem-akka.actor.default-dispatcher-2] INFO  Remoting - Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@192.168.1.145:49786]
[info] 21:47:18.305 [main] INFO  o.spark-project.jetty.server.Server - jetty-8.y.z-SNAPSHOT
[info] 21:47:18.371 [main] INFO  o.s.jetty.server.AbstractConnector - Started SelectChannelConnector@0.0.0.0:4040
[error] log4j:WARN No appenders could be found for logger (kafka.utils.VerifiableProperties).
[error] log4j:WARN Please initialize the log4j system properly.
[error] log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[info] 21:47:19.903 [main] ERROR o.a.spark.streaming.StreamingContext - Error starting the context, marking it as stopped
[info] java.io.NotSerializableException: DStream checkpointing has been enabled but the DStreams with their functions are not serializable
[info] org.mkuthan.spark.KafkaDStreamSink
[info] Serialization stack:
[info] 	- object not serializable (class: org.mkuthan.spark.KafkaDStreamSink, value: org.mkuthan.spark.KafkaDStreamSink@2274160)
[error] Exception in thread "main" java.io.NotSerializableException: DStream checkpointing has been enabled but the DStreams with their functions are not serializable
[info] 	- field (class: org.mkuthan.spark.KafkaDStreamSink$$anonfun$sendToKafka$1, name: $outer, type: class org.mkuthan.spark.KafkaDStreamSink)
[error] org.mkuthan.spark.KafkaDStreamSink
[error] Serialization stack:
[error] 	- object not serializable (class: org.mkuthan.spark.KafkaDStreamSink, value: org.mkuthan.spark.KafkaDStreamSink@2274160)
[error] 	- field (class: org.mkuthan.spark.KafkaDStreamSink$$anonfun$sendToKafka$1, name: $outer, type: class org.mkuthan.spark.KafkaDStreamSink)
[error] 	- object (class org.mkuthan.spark.KafkaDStreamSink$$anonfun$sendToKafka$1, <function1>)
[error] 	- field (class: org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3, name: cleanedF$1, type: interface scala.Function1)
[error] 	- object (class org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3, <function2>)
[error] 	- writeObject data (class: org.apache.spark.streaming.dstream.DStream)
[error] 	- object (class org.apache.spark.streaming.dstream.ForEachDStream, org.apache.spark.streaming.dstream.ForEachDStream@43a09ce2)
[error] 	- element of array (index: 0)
[error] 	- array (class [Ljava.lang.Object;, size 16)
[error] 	- field (class: scala.collection.mutable.ArrayBuffer, name: array, type: class [Ljava.lang.Object;)
[error] 	- object (class scala.collection.mutable.ArrayBuffer, ArrayBuffer(org.apache.spark.streaming.dstream.ForEachDStream@43a09ce2))
[error] 	- writeObject data (class: org.apache.spark.streaming.dstream.DStreamCheckpointData)
[error] 	- object (class org.apache.spark.streaming.dstream.DStreamCheckpointData, [
[error] 0 checkpoint files 
[error] 
[error] ])
[error] 	- writeObject data (class: org.apache.spark.streaming.dstream.DStream)
[error] 	- object (class org.apache.spark.streaming.kafka.DirectKafkaInputDStream, org.apache.spark.streaming.kafka.DirectKafkaInputDStream@1b495d4)
[error] 	- element of array (index: 0)
[error] 	- array (class [Ljava.lang.Object;, size 16)
[error] 	- field (class: scala.collection.mutable.ArrayBuffer, name: array, type: class [Ljava.lang.Object;)
[error] 	- object (class scala.collection.mutable.ArrayBuffer, ArrayBuffer(org.apache.spark.streaming.kafka.DirectKafkaInputDStream@1b495d4))
[error] 	- writeObject data (class: org.apache.spark.streaming.DStreamGraph)
[error] 	- object (class org.apache.spark.streaming.DStreamGraph, org.apache.spark.streaming.DStreamGraph@30c1da48)
[error] 	- field (class: org.apache.spark.streaming.Checkpoint, name: graph, type: class org.apache.spark.streaming.DStreamGraph)
[error] 	- object (class org.apache.spark.streaming.Checkpoint, org.apache.spark.streaming.Checkpoint@376c7d7d)
[error] 	at org.apache.spark.streaming.StreamingContext.validate(StreamingContext.scala:557)
[error] 	at org.apache.spark.streaming.StreamingContext.liftedTree1$1(StreamingContext.scala:601)
[error] 	at org.apache.spark.streaming.StreamingContext.start(StreamingContext.scala:600)
[error] 	at org.mkuthan.spark.SparkStreamingApplication$$anonfun$withSparkStreamingContext$1.apply(SparkStreamingApplication.scala:37)
[error] 	at org.mkuthan.spark.SparkStreamingApplication$$anonfun$withSparkStreamingContext$1.apply(SparkStreamingApplication.scala:31)
[error] 	at org.mkuthan.spark.SparkApplication$class.withSparkContext(SparkApplication.scala:32)
[error] 	at example.WordCountJob.withSparkContext(WordCountJob.scala:24)
[error] 	at org.mkuthan.spark.SparkStreamingApplication$class.withSparkStreamingContext(SparkStreamingApplication.scala:31)
[error] 	at example.WordCountJob.withSparkStreamingContext(WordCountJob.scala:24)
[error] 	at example.WordCountJob.start(WordCountJob.scala:33)
[error] 	at example.WordCountJob$.main(WordCountJob.scala:73)
[error] 	at example.WordCountJob.main(WordCountJob.scala)
[info] 	- object (class org.mkuthan.spark.KafkaDStreamSink$$anonfun$sendToKafka$1, <function1>)
[info] 	- field (class: org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3, name: cleanedF$1, type: interface scala.Function1)
[info] 	- object (class org.apache.spark.streaming.dstream.DStream$$anonfun$foreachRDD$1$$anonfun$apply$mcV$sp$3, <function2>)
[info] 	- writeObject data (class: org.apache.spark.streaming.dstream.DStream)
[info] 	- object (class org.apache.spark.streaming.dstream.ForEachDStream, org.apache.spark.streaming.dstream.ForEachDStream@43a09ce2)
[info] 	- element of array (index: 0)
[info] 	- array (class [Ljava.lang.Object;, size 16)
[info] 	- field (class: scala.collection.mutable.ArrayBuffer, name: array, type: class [Ljava.lang.Object;)
[info] 	- object (class scala.collection.mutable.ArrayBuffer, ArrayBuffer(org.apache.spark.streaming.dstream.ForEachDStream@43a09ce2))
[info] 	- writeObject data (class: org.apache.spark.streaming.dstream.DStreamCheckpointData)
[info] 	- object (class org.apache.spark.streaming.dstream.DStreamCheckpointData, [
[info] 0 checkpoint files 
[info] 
[info] ])
[info] 	- writeObject data (class: org.apache.spark.streaming.dstream.DStream)
[info] 	- object (class org.apache.spark.streaming.kafka.DirectKafkaInputDStream, org.apache.spark.streaming.kafka.DirectKafkaInputDStream@1b495d4)
[info] 	- element of array (index: 0)
[info] 	- array (class [Ljava.lang.Object;, size 16)
[info] 	- field (class: scala.collection.mutable.ArrayBuffer, name: array, type: class [Ljava.lang.Object;)
[info] 	- object (class scala.collection.mutable.ArrayBuffer, ArrayBuffer(org.apache.spark.streaming.kafka.DirectKafkaInputDStream@1b495d4))
[info] 	- writeObject data (class: org.apache.spark.streaming.DStreamGraph)
[info] 	- object (class org.apache.spark.streaming.DStreamGraph, org.apache.spark.streaming.DStreamGraph@30c1da48)
[info] 	- field (class: org.apache.spark.streaming.Checkpoint, name: graph, type: class org.apache.spark.streaming.DStreamGraph)
[info] 	- object (class org.apache.spark.streaming.Checkpoint, org.apache.spark.streaming.Checkpoint@376c7d7d)
[info] 	at org.apache.spark.streaming.StreamingContext.validate(StreamingContext.scala:557) [spark-streaming_2.11-1.6.0.jar:1.6.0]
[info] 	at org.apache.spark.streaming.StreamingContext.liftedTree1$1(StreamingContext.scala:601) [spark-streaming_2.11-1.6.0.jar:1.6.0]
[info] 	at org.apache.spark.streaming.StreamingContext.start(StreamingContext.scala:600) [spark-streaming_2.11-1.6.0.jar:1.6.0]
[info] 	at org.mkuthan.spark.SparkStreamingApplication$$anonfun$withSparkStreamingContext$1.apply(SparkStreamingApplication.scala:37) [classes/:na]
[info] 	at org.mkuthan.spark.SparkStreamingApplication$$anonfun$withSparkStreamingContext$1.apply(SparkStreamingApplication.scala:31) [classes/:na]
[info] 	at org.mkuthan.spark.SparkApplication$class.withSparkContext(SparkApplication.scala:32) [classes/:na]
[info] 	at example.WordCountJob.withSparkContext(WordCountJob.scala:24) [classes/:na]
[info] 	at org.mkuthan.spark.SparkStreamingApplication$class.withSparkStreamingContext(SparkStreamingApplication.scala:31) [classes/:na]
[info] 	at example.WordCountJob.withSparkStreamingContext(WordCountJob.scala:24) [classes/:na]
[info] 	at example.WordCountJob.start(WordCountJob.scala:33) [classes/:na]
[info] 	at example.WordCountJob$.main(WordCountJob.scala:73) [classes/:na]
[info] 	at example.WordCountJob.main(WordCountJob.scala) [classes/:na]
[info] 21:47:19.941 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/metrics/json,null}
[info] 21:47:19.941 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/stages/stage/kill,null}
[info] 21:47:19.941 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/api,null}
[info] 21:47:19.941 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/,null}
[info] 21:47:19.941 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/static,null}
[info] 21:47:19.942 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/executors/threadDump/json,null}
[info] 21:47:19.942 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/executors/threadDump,null}
[info] 21:47:19.942 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/executors/json,null}
[info] 21:47:19.943 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/executors,null}
[info] 21:47:19.943 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/environment/json,null}
[info] 21:47:19.943 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/environment,null}
[info] 21:47:19.943 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/storage/rdd/json,null}
[info] 21:47:19.943 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/storage/rdd,null}
[info] 21:47:19.943 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/storage/json,null}
[info] 21:47:19.943 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/storage,null}
[info] 21:47:19.943 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/stages/pool/json,null}
[info] 21:47:19.943 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/stages/pool,null}
[info] 21:47:19.944 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/stages/stage/json,null}
[info] 21:47:19.944 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/stages/stage,null}
[info] 21:47:19.944 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/stages/json,null}
[info] 21:47:19.944 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/stages,null}
[info] 21:47:19.944 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/jobs/job/json,null}
[info] 21:47:19.944 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/jobs/job,null}
[info] 21:47:19.944 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/jobs/json,null}
[info] 21:47:19.944 [Thread-2] INFO  o.s.j.server.handler.ContextHandler - stopped o.s.j.s.ServletContextHandler{/jobs,null}
java.lang.RuntimeException: Nonzero exit code returned from runner: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last compile:run for the full output.
[error] (compile:run) Nonzero exit code returned from runner: 1
[error] Total time: 5 s, completed Dec 13, 2017 9:47:20 PM
```

**Comment by mkuthan** [comment]
Thanks for report, I will take a look.
